# Generated by Django 4.2.14 on 2024-07-23 08:27

from django.db import migrations
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('objects', main_app.models.CustomStudentManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
                ('objects', main_app.models.CustomTeacherManager()),
            ],
        ),
    ]
